package africa.skunkworks.training.drools.insurance.lesson04.demo02;

import africa.skunkworks.training.drools.insurance.domain.dto.ClaimDto;
import africa.skunkworks.training.drools.insurance.domain.dto.PolicyDto;
import africa.skunkworks.training.drools.insurance.domain.enums.Status
import africa.skunkworks.training.drools.insurance.domain.dto.Payout;

rule "Issue Payout"
    dialect "java"
    salience 0
    when
        $claim: ClaimDto(status == Status.APPROVED)
    then
        Payout payout = new Payout( $claim.getPolicyNumber(), $claim.getClaimAmount() );
        insert( payout );
        modify($claim){
            setReason("New Payout: " + payout + " Issued")
        }
end