DROP SCHEMA IF EXISTS DROOLS_TRAINING_INSURANCE CASCADE;

-- create schema
CREATE SCHEMA IF NOT EXISTS DROOLS_TRAINING_INSURANCE;

-- Drop Tables
DROP TABLE IF EXISTS DROOLS_TRAINING_INSURANCE.APPLICATION;
DROP TABLE IF EXISTS DROOLS_TRAINING_INSURANCE.POLICY;
DROP TABLE IF EXISTS DROOLS_TRAINING_INSURANCE.CLAIM;
DROP TABLE IF EXISTS DROOLS_TRAINING_INSURANCE.CLIENT_IDENTIFICATION;
DROP TABLE IF EXISTS DROOLS_TRAINING_INSURANCE.CLIENT;

-- CREATE TABLES
CREATE TABLE DROOLS_TRAINING_INSURANCE.CLIENT (
    CLIENT_ID VARCHAR(20),
    CLIENT_NAME VARCHAR(100),
    BIRTHDATE DATE,
    IS_SMOKER BOOLEAN,
    IS_EMPLOYED BOOLEAN,
    ANNUAL_INCOME NUMERIC(14,4),
    CONSTRAINT CLIENT_PK PRIMARY KEY (CLIENT_ID)
);

-- CLIENT IDENTIFICATION
CREATE TABLE DROOLS_TRAINING_INSURANCE.CLIENT_IDENTIFICATION(
    IDENTIFICATION_NUMBER VARCHAR(20),
    CLIENT_ID VARCHAR(20),
    IS_EXPIRED BOOLEAN,
    CONSTRAINT IDENTIFICATION_PK PRIMARY KEY (IDENTIFICATION_NUMBER),
    CONSTRAINT IDENTIFICATION_FK FOREIGN KEY (CLIENT_ID) REFERENCES DROOLS_TRAINING_INSURANCE.CLIENT
);

-- APPLICATION
CREATE TABLE DROOLS_TRAINING_INSURANCE.APPLICATION(
    APPLICATION_NUMBER VARCHAR(20),
    CLIENT_ID VARCHAR(20),
    PEC BOOLEAN,
    RISK VARCHAR(20),
    BMI VARCHAR(20),
    REASON VARCHAR(50) DEFAULT 'N/A',
    CONSTRAINT APPLICATION_PK PRIMARY KEY (APPLICATION_NUMBER),
    CONSTRAINT APPLICATION_FK FOREIGN KEY (CLIENT_ID) REFERENCES DROOLS_TRAINING_INSURANCE.CLIENT
);

-- POLICY
CREATE TABLE DROOLS_TRAINING_INSURANCE.POLICY(
  POLICY_NUMBER VARCHAR(20),
  CLIENT_ID VARCHAR(20),
  PREMIUM NUMERIC (14,4),
  COVERAGE NUMERIC(14,4),
  STATUS VARCHAR(10),
  CONSTRAINT POLICY_PK PRIMARY KEY (POLICY_NUMBER),
  CONSTRAINT POLICY_FK FOREIGN KEY (CLIENT_ID) REFERENCES DROOLS_TRAINING_INSURANCE.CLIENT
);

-- CLAIMS
CREATE TABLE DROOLS_TRAINING_INSURANCE.CLAIM(
  CLAIM_ID VARCHAR(20),
  POLICY_NUMBER VARCHAR(20),
  DATE_OF_CLAIM DATE,
  CLAIM_AMOUNT NUMERIC(14,4),
  CONSTRAINT CLAIM_PK PRIMARY KEY (CLAIM_ID),
  CONSTRAINT CLAIM_FK FOREIGN KEY (POLICY_NUMBER) REFERENCES DROOLS_TRAINING_INSURANCE.POLICY
);