package africa.skunkworks.training.drools.insurance.claim;

import africa.skunkworks.training.drools.insurance.domain.dto.ClaimDto;
import africa.skunkworks.training.drools.insurance.domain.enums.Status
import africa.skunkworks.training.drools.insurance.domain.dto.Payout;

dialect  "java"

rule "Valid Claims"
    agenda-group "valid-claim"
    when
        $claim: ClaimDto( status == Status.PENDING )
    then
    modify($claim) {
        setReason($claim + ": not invalidated. Approval Granted"),
        setStatus(Status.APPROVED)
    }
end

rule "Issue Payout"
    agenda-group "issue-payout"
    when
        $claim: ClaimDto(status == Status.APPROVED)
    then
        Payout payout = new Payout( $claim.getPolicyNumber(), $claim.getClaimAmount() );
        insert( payout );
        modify($claim){
            setReason("New Payout: " + payout + " Issued")
        }
end
