package org.sw.lesson04.demo2;

import org.sw.facts.Claim;
import org.sw.facts.Status;
import org.sw.facts.Payout;

rule "Issue Payout"
    dialect "java"
    salience 0
    when
        $claim: Claim(status == Status.APPROVED)
    then
        Payout payout = new Payout( $claim.getPolicyNumber(), $claim.getClaimAmount() );
        System.out.println("New Payout: " + payout + " Issued");
        insert( payout );
end