package africa.skunkworks.training.drools.insurance.lesson01.demo04;

import africa.skunkworks.training.drools.insurance.domain.dto.ApplicationDto;

global africa.skunkworks.training.drools.insurance.domain.response.ApplicationResponse applicationResponse;

dialect  "java"

rule "Invalid application - minor"
    when
       $application: ApplicationDto ($clientAge: clientAge < 18)
    then
       applicationResponse.setStatus("DENIED");
end

rule "Invalid application - unemployed"
    when
      $application: ApplicationDto( $employed: isEmployed )
    then
      applicationResponse.setStatus("DENIED");
end

rule "Invalid application - Pre-existing Condition"
    when
        $application: ApplicationDto( pec )
    then
        applicationResponse.setStatus("DENIED");
end

rule "Valid Application"
    when
         $application: ApplicationDto (!pec, isEmployed, clientAge >= 18)
    then
         applicationResponse.setStatus("APPROVED");
end